In [409]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [410]:
df = pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [411]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [412]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [413]:
df.duplicated().sum()

np.int64(0)

In [414]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [415]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [416]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [417]:
print(df.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [418]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [419]:
pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,9997,15569892,Johnstone,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,9998,15584532,Liu,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,9999,15682355,Sabbatini,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,10000,15628319,Walker,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [420]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [421]:
x = df.drop(columns=['Exited'])
y = df['Exited']

In [422]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [423]:
x

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [424]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [425]:
x_train.shape

(8000, 13)

In [426]:
print(x_train.dtypes)

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [427]:
x_train = x_train.drop(columns=['Surname'], errors='ignore')
x_test = x_test.drop(columns=['Surname'], errors='ignore')
#rop(columns=['Surname']) coz it was text data

In [428]:
import pandas as pd

x_train = pd.get_dummies(x_train, drop_first=True)
x_test = pd.get_dummies(x_test, drop_first=True)
#This function is used for encoding categorical (text) data into numbers

In [429]:
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

In [430]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [431]:
x_train_scaled
#scaling of x is done

array([[-0.80531942,  0.42399976, -0.23082038, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [ 0.04247882, -1.02496943, -0.25150912, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.84899177,  1.18230224, -0.3963303 , ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [-1.42539753, -0.21286544,  0.22433188, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.06050233, -1.16325633,  0.13123255, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-1.65762353,  1.14029686,  1.1656695 , ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [432]:
import tensorflow
from tensorflow import keras 
from tensorflow.keras import Sequential #Imports the Sequential model
from tensorflow.keras.layers import Dense #Imports Dense layer means: Every neuron is connected to every neuron in the next layer (fully connected layer)

In [433]:
model = Sequential() 
model.add(Dense(1,activation='relu', input_dim = 13))
#sequential model is used for training
#first used sigmoid then relu for incresing accuracy

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [434]:
model.summary()
#summary of the parameters

Model: "sequential_30"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 1)              │            14 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14 (56.00 B)

 Trainable params: 14 (56.00 B)

 Non-trainable params: 0 (0.00 B)

In [435]:
model.compile(loss="binary_crossentropy",optimizer="Adam")
#binary loss function is used and optimizer Adam is used as it is most efficient

In [436]:
model.fit(x_train_scaled, y_train, epochs=15)
#model is trained now

Epoch 1/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.6747
Epoch 2/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.3666
Epoch 3/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.2499
Epoch 4/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.1367
Epoch 5/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9172
Epoch 6/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7043
Epoch 7/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.6541
Epoch 8/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5080
Epoch 9/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.4290
Epoch 10/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3378
Epoch 11/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4322
Epoch 12/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3416
Epoch 13/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2508
Epoch 14/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.1795
Epoch 15/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.1499

In [437]:
model.layers[0].get_weights()
#Will tell us the weights

[array([[ 0.27219662],
        [-0.02869257],
        [-0.2001514 ],
        [ 0.4705112 ],
        [-0.20813599],
        [-0.09225368],
        [-0.4891802 ],
        [ 0.08735923],
        [-0.19772978],
        [ 0.0909913 ],
        [-0.04993466],
        [-0.1623037 ],
        [-0.09023402]], dtype=float32),
 array([-0.2479082], dtype=float32)]

In [438]:
y_log = model.predict(x_test_scaled)
#everything stored in a single variable

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [439]:
y_pred = np.where(y_log>0.5,1,0)
#if y_log id greater than 0.5 it willl give 1 elso 0

In [440]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7825